# Travis CI Configuration File
sudo: false
dist: trusty
language: php
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor
env:
  global:
    - WP_VERSION=latest WP_MULTISITE=0

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

# PHP/WP versions
matrix:
  fast_finish: true
  include:
  - name: "Coding standard check"
    php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
  - name: "Unit tests code coverage"
    php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  - name: "Object Sync for Salesforce unit tests using WordPress nightly"
    php: 7.3
    env: WP_VERSION=nightly WP_MULTISITE=0
  - php: 7.4snapshot
    env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
  - php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  - php: 7.4snapshot
    env: WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
  - export WP_CORE_DIR=/tmp/wordpress/
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - composer install --no-dev
  - |
    # Install WP Test suite, install PHPUnit globally:
    if [[ ! -z "$WP_VERSION" ]]; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=5.7.*|7.5.*"
    fi
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
