blank_issues_enabled: false
contact_links:
  - name: WordPress Support Forum
    url: https://wordpress.org/support/plugin/object-sync-for-salesforce/
    about: We make an effort to answer support requests in the WordPress Support forum. If you have these requests, please put them in that forum only.
